bb.bundle.toolbar.get_config:
    pattern: /rest/{version}/toolbar/config
    defaults:
        _controller: BackBeeToolbarBundle:Config:get
    requirements:
        version: \d
        _method: GET
