bb.test:
    path: /test
    defaults:
        _controller: BackBeeWebBundle:Default:index

# BackBee resources
bb.classcontent_thumbnail:
    path: /%bbapp.routing.resource_uri_prefix%/%classcontent_thumbnail.base_folder%/{filename}
    defaults:
        _controller: BackBeeCoreDomainBundle:Resource:getClassContentThumbnail
    requirements:
        filename: .+

# @todo gvf this should be done via assetic or whatever not via controller
#bb.resources:
#    path: /%bbapp.routing.resource_uri_prefix%/{filename}
#    defaults:
#        _controller: BackBeeCoreDomainBundle:Resource:resources
#    requirements:
#        filename: .+

# BackBee media files
# @todo gvf
#bb.images:
#    path: /{type}/{filename}
#    defaults:
#        _action: mediaAction
#        _controller: BackBeeCoreDomainBundle:Media:media
#    requirements:
#        type: (%bbapp.routing.image_uri_prefix%|%bbapp.routing.media_uri_prefix%)
#        filename: .+


# BackBee rss
bb.rss:
    path: /rss/{uri}
    defaults:
        _action: rssAction
        uri:     _root_
    requirements:
        uri: .+

# Default route
bb.default:
    path: /{uri}
    defaults:
        _controller: BackBeeWebBundle:Default:default
        uri: ''