parameters:
        bbapp.renderer.class: BackBee\WebBundle\Renderer\Renderer
services:
#    back_bee_web.example:
#        class: BackBee\WebBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    renderer:
        class:      %bbapp.renderer.class%
        arguments:
            - @templating
            - @doctrine.orm.entity_manager
            - @event_dispatcher
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }