parameters:
        bbapp.context: ~
        # not sure what these 2 are used for, it's not symfony env for sure
        bbapp.environment: ~
        environment: ~

        # set default backbee base directory, config directory and repository directory
        bbapp.base.dir: ~
        bbapp.config.dir: ~
        bbapp.repository.dir: ~

        # define data directory
        bbapp.data.dir: ~

        # define media directory
        bbapp.media.dir: ~
services:
#    back_bee_core.example:
#        class: BackBee\Bundle\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    site:
        class: BackBee\CoreDomain\Site\Site
        arguments:
            - 0ab498464671a28d34c8b1511867e9d7
        calls:
            - [setLabel, ['Reiss']]
            - [setServerName, ['backbee-beta.dev']]
