parameters:
        bbapp.context: ~
        # not sure what these 2 are used for, it's not symfony env for sure
        bbapp.environment: ~
        environment: ~

        # set default backbee base directory, config directory and repository directory
        bbapp.base.dir: ~
        bbapp.config.dir: ~
        bbapp.repository.dir: ~

        # define media directory
        bbapp.media.dir: ~
services:

