services:
    bb.context.resource_dir:
        class: ResourceDirContext
        arguments:
            - %bbapp.base.repository.dir%

    # ----------------- EVENT LISTENERS --------------------
    nestednode.page_listener:
        arguments:
            - @doctrine.orm.default_entity_manager
            - @security.authorization_checker
        class: BackBee\CoreDomainBundle\Event\Listener\PageListener
        tags:
            - { name: "kernel.event_listener", event: "nestednode.page.postload", method: onPostLoad }
            - { name: "kernel.event_listener", event: "nestednode.section.preupdate", method: onPreUpdate }
            - { name: "kernel.event_listener", event: "nestednode.page.preupdate", method: onPreUpdate }
            - { name: "kernel.event_listener", event: "nestednode.page.onflush", method: onFlushPage }

    classcontent_listener:
        class: BackBee\CoreDomainBundle\ClassContent\Listener\AbstractClassContentListener
        arguments:
            - @service_container
        tags:
            - { name: "kernel.event_listener", event: "classcontent.include", method: onInclude }
            - { name: doctrine.event_listener, event: postLoad}

#
#classcontent.update:
#    listeners:
#        - [BackBee\CoreDomain\ClassContent\Listener\ClassContentListener, onUpdate]
#
#classcontent.onflush:
#    listeners:
#        - [BackBee\CoreDomain\ClassContent\Listener\ClassContentListener, onFlushContent]
#        - [BackBee\CoreDomain\ClassContent\Listener\RevisionListener, onFlushContent]
#        - [BackBee\CoreDomain\ClassContent\Listener\IndexationListener, onFlushContent]
#        - [@cache.listener, onFlushContent]
#        - [BackBee\Event\Listener\MetaDataListener, onFlushContent]
#        - [BackBee\Event\Listener\RewritingListener, onFlushContent]
#
#classcontent.preremove:
#    listeners:
#        - [BackBee\CoreDomain\ClassContent\Listener\ClassContentListener, onPreRemove]
#
#classcontent.prerender:
#    listeners:
#        - [BackBee\CoreDomain\ClassContent\Listener\RevisionListener, onPrerenderContent]
#        - [@cache.listener, onPreRenderContent]
#
#classcontent.postrender:
#    listeners:
#        - [@cache.listener, onPostRenderContent]
#
#rest.controller.classcontentcontroller.getaction.postcall:
#  listeners:
#    - [BackBee\CoreDomain\ClassContent\Listener\ClassContentListener, onPostCall]
#
#element.file.postremove:
#    listeners:
#        - [BackBee\CoreDomain\ClassContent\Listener\ClassContentListener, onRemoveElementFile]
#
#nestednode.page.prerender:
#    listeners:
#        - [@cache.listener, onPreRenderPage]
#
#nestednode.page.preupdate:
#    listeners:
#        - [BackBee\CoreDomain\Workflow\Listener\PageListener, onPreUpdate]
#
#nestednode.page.postrender:
#    listeners:
#        - [@cache.listener, onPostRenderPage]
#
#nestednode.page.onflush:
#    listeners:
#        - [BackBee\Event\Listener\MetaDataListener, onFlushPage]
#        - [BackBee\CoreDomain\ClassContent\Listener\IndexationListener, onFlushPage]
#        - [BackBee\Event\Listener\RewritingListener, onFlushPage]
#        - [@cache.listener, onFlushPage]
#
#site.layout.prepersist:
#    listeners:
#        - [BackBee\Event\Listener\LayoutListener, onBeforeSave]
#
#site.layout.preupdate:
#    listeners:
#        - [BackBee\Event\Listener\LayoutListener, onBeforeSave]
#
#site.layout.postremove:
#    listeners:
#        - [BackBee\Event\Listener\LayoutListener, onAfterRemove]
#
#revision.postload:
#    listeners:
#        - [BackBee\CoreDomain\ClassContent\Listener\RevisionListener, onPostLoad]
#
#revision.onflush:
#    listeners:
#        - [BackBee\CoreDomain\ClassContent\Listener\RevisionListener, onFlushElementFile]
#
#element.keyword.render:
#    listeners:
#        - [BackBee\Event\Listener\elementListener, onRender]
#
#frontcontroller.request:
#    listeners:
#        - [@rest.listener.body, onRequest]
#
#kernel.exception:
#    listeners:
#        - [@rest.listener.exception, onKernelException]
#        - [@exception.listener, onKernelException]
#
#kernel.controller:
#    listeners:
#        - [@rest.listener.param_converter, onKernelController]
#        - [@rest.listener.security, onKernelController]
#        - [@rest.listener.validation, onKernelController]
#        - [@rest.listener.pagination, onKernelController]
#
#kernel.response:
#    listeners:
#        - [@profiler.toolbar.listener, onKernelResponse]
#        - [@profiler.listener, onKernelResponse]
#
#bbapplication.init:
#    listeners:
#        - [BackBee\DependencyInjection\Listener\ContainerListener, onApplicationInit]
#        - [BackBee\CoreDomain\ClassContent\Listener\ClassContentListener, onApplicationInit]
#
#
#
#bbapplication.start:
#    listeners:
#        - [BackBee\Renderer\Listener\TwigListener, onApplicationStart]
#
#service.tagged.config_per_site:
#    listeners:
#        - [@config.configurator, onGetServiceConfig]
#
#bbapplication.stop:
#    listeners:
#        - [BackBee\Bundle\Listener\BundleListener, onApplicationStop]
#            