<!DOCTYPE html>
<html>
	<head>
    </head>
    <body>
        <?php echo $this->bbtoolbar(); ?>

        <!-- BB5 SITE WRAPPER -->
        <div id="bb5-site-wrapper">
            <!-- BEGIN bodywrapper: .container -->
            <div class="container" id="body-wrapper">
                <!-- bodywrapper -->
                <div class="row" id="bb5-mainLayoutRow">
                </div>
                <!-- /end bodywrapper -->
            </div>
            <!-- END bodywrapper -->
        </div>
        <!-- END BB5 SITE WRAPPER -->

    </body>
</html>
